name = "meta"
type = "javascript"
zone_id = ""
account_id = "49f956d76e89a09b797eafdfbffd4b07"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
